# SPDX-FileCopyrightText: 2020-2023 Gilles Caulier <caulier dot gilles at gmail dot com>
# SPDX-License-Identifier: CC0-1.0
#
# See targets available at https://invent.kde.org/sysadmin/ci-utilities/-/tree/master/gitlab-templates

include:
  - project: sysadmin/ci-utilities
    file:

      # --- CI Validators ---

      # - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/json-validation.yml
      - /gitlab-templates/xml-lint.yml

      # --- Continuous Integration Qt6 ---

      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/windows-qt6.yml
      - /gitlab-templates/freebsd-qt6.yml

      # --- Continuous Deployement Qt6 ---

      # - /gitlab-templates/craft-appimage-qt6.yml
      # - /gitlab-templates/craft-windows-x86-64-qt6.yml
